import assert from "node:assert/strict";
import { mkdtempSync,rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, before, describe, it } from "node:test";
import { loadConfig } from "../src/config/env.mjs";
import { createApp } from "../src/http/app.mjs";
import { JobNotRetryableError,OperationsCursorError,OperationsJobNotFoundError } from "../src/storage/operations-store.mjs";

describe("operations API",()=>{let server,base,dir;const key="test-admin-key";let retried;
  before(async()=>{dir=mkdtempSync(join(tmpdir(),"operations-api-"));const config=loadConfig({NODE_ENV:"test",PORT:0,DATABASE_FILE_PATH:join(dir,"db.sqlite"),PUBLIC_ORIGIN:"http://sitepulse.test",AUTH_REGISTRATION_MODE:"closed",ADMIN_API_KEY:key});const page={items:[{id:"job-1",createdAt:"2026-09-01T00:00:00.000Z",failedAt:"2026-09-02T00:00:00.000Z",attemptCount:2,maxAttempts:2,errorCode:"AUDIT_FAILED",planCode:"free",requestId:null}],nextCursor:null};server=createApp(config,{operationsStore:{snapshot:()=>({database:{reachable:true},queue:{queued:0},recent:{},api:{},users:{active:0},quota:{totalUsed:0}}),listFailed:({cursor})=>{if(cursor==="bad")throw new OperationsCursorError();return page},listAuditLog:()=>({items:[],nextCursor:null}),retryJob:({jobId})=>{retried=jobId;if(jobId==="missing")throw new OperationsJobNotFoundError();if(jobId==="queued")throw new JobNotRetryableError();return{id:jobId,status:"queued"}}}});await new Promise(r=>server.listen(0,"127.0.0.1",r));base=`http://127.0.0.1:${server.address().port}`});
  after(async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));rmSync(dir,{recursive:true,force:true})});
  it("requires admin access and private no-store",async()=>{for(const headers of [{},{"X-Admin-Key":"wrong"}])assert.equal((await fetch(`${base}/api/operations`,{headers})).status,403);const response=await fetch(`${base}/api/operations`,{headers:{"X-Admin-Key":key}});assert.equal(response.status,200);assert.match(response.headers.get("cache-control"),/private.*no-store/)});
  it("returns safe failed jobs and rejects malformed cursor",async()=>{const response=await fetch(`${base}/api/operations/failed`,{headers:{"X-Admin-Key":key}});assert.equal(response.status,200);assert.deepEqual((await response.json()).jobs[0],{id:"job-1",createdAt:"2026-09-01T00:00:00.000Z",failedAt:"2026-09-02T00:00:00.000Z",attemptCount:2,maxAttempts:2,errorCode:"AUDIT_FAILED",planCode:"free",requestId:null});assert.equal((await fetch(`${base}/api/operations/failed?cursor=bad`,{headers:{"X-Admin-Key":key}})).status,400)});
  it("requires trusted Origin for retry and maps safe errors",async()=>{assert.equal((await fetch(`${base}/api/operations/jobs/job-1/retry`,{method:"POST",headers:{"X-Admin-Key":key}})).status,403);assert.equal((await fetch(`${base}/api/operations/jobs/job-1/retry`,{method:"POST",headers:{"X-Admin-Key":key,Origin:"https://foreign.test"}})).status,403);const accepted=await fetch(`${base}/api/operations/jobs/job-1/retry`,{method:"POST",headers:{"X-Admin-Key":key,Origin:"http://sitepulse.test"}});assert.equal(accepted.status,202);assert.equal(retried,"job-1");assert.equal((await fetch(`${base}/api/operations/jobs/missing/retry`,{method:"POST",headers:{"X-Admin-Key":key,Origin:"http://sitepulse.test"}})).status,404);const conflict=await fetch(`${base}/api/operations/jobs/queued/retry`,{method:"POST",headers:{"X-Admin-Key":key,Origin:"http://sitepulse.test"}});assert.equal(conflict.status,409);assert.equal((await conflict.json()).error.code,"JOB_NOT_RETRYABLE")});
});
