import { expect,test } from "@playwright/test";
const overview={database:{reachable:true},queue:{queued:2,running:1,failed:1,completed:8,oldestQueuedAgeMs:3000},recent:{completed:4,failed:1,failureRate:.2,completionLatencyAvgMs:450},api:{requests:20,errors:1,dbErrors:0,latencyAvgMs:12,latencyMaxMs:40},users:{active:5,free:4,pro:1,deletionPending:1,disabled:1},quota:{periodStart:"2026-09-01T00:00:00.000Z",resetsAt:"2026-10-01T00:00:00.000Z",totalUsed:9,freeUsed:5,proUsed:4,usersAtLimit:1}};
const failed={jobs:[{id:"job-safe",createdAt:"2026-09-20T00:00:00.000Z",failedAt:"2026-09-21T00:00:00.000Z",attemptCount:2,maxAttempts:2,errorCode:"AUDIT_FAILED",planCode:"free",requestId:null}],page:{nextCursor:null}};
const activity={entries:[{createdAt:"2026-09-22T00:00:00.000Z",action:"job.retry",targetType:"audit_job",targetId:"job-old",outcome:"accepted",requestId:null}],page:{nextCursor:null}};
async function mock(page,{wrong=false,retryStatus=202,failedStatus=200}={}){await page.route("**/api/operations**",route=>{const request=route.request(),url=new URL(request.url());if(request.method()==="POST")return route.fulfill({status:retryStatus,contentType:"application/json",body:JSON.stringify(retryStatus===202?{job:{id:"job-safe",status:"queued"}}:{error:{code:"JOB_NOT_RETRYABLE",message:"safe"}})});if(wrong)return route.fulfill({status:403,contentType:"application/json",body:'{"error":{"code":"ADMIN_ACCESS_REQUIRED"}}'});if(url.pathname.endsWith("/failed"))return route.fulfill({status:failedStatus,contentType:"application/json",body:JSON.stringify(failedStatus===200?failed:{error:{code:"UNAVAILABLE"}})});if(url.pathname.endsWith("/audit-log"))return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(activity)});return route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(overview)})})}
async function connect(page,key="valid"){await page.goto("/admin");await page.locator("#adminKey").fill(key);await page.getByRole("button",{name:"Connect"}).click()}
test("admin shell exposes no operations data before access",async({page})=>{await page.goto("/admin");await expect(page.getByText("System overview")).toBeHidden();await expect(page.getByText("Admin access")).toBeVisible()});
test("wrong key shows access error",async({page})=>{await mock(page,{wrong:true});await connect(page,"wrong");await expect(page.locator("#accessStatus")).toContainText("denied")});
test("correct key opens dashboard",async({page})=>{await mock(page);await connect(page);await expect(page.getByText("System overview")).toBeVisible()});
test("key input uses password type",async({page})=>{await page.goto("/admin");await expect(page.locator("#adminKey")).toHaveAttribute("type","password")});
test("key is absent from browser persistence and URL",async({page,context})=>{await mock(page);await connect(page,"memory-secret");expect(page.url()).not.toContain("memory-secret");expect(await page.evaluate(()=>({local:[...Object.keys(localStorage)],session:[...Object.keys(sessionStorage)],html:document.documentElement.outerHTML.includes("memory-secret")}))).toEqual({local:[],session:[],html:false});expect((await context.cookies()).some(c=>c.value.includes("memory-secret"))).toBe(false)});
test("metrics render",async({page})=>{await mock(page);await connect(page);await expect(page.locator("#queue")).toContainText("2");await expect(page.locator("#users")).toContainText("5")});
test("failed jobs render safe fields",async({page})=>{await mock(page);await connect(page);await expect(page.locator("#failed")).toContainText("AUDIT_FAILED")});
test("retry requires confirmation",async({page})=>{await mock(page);await connect(page);await page.getByRole("button",{name:"Retry",exact:true}).click();await expect(page.getByRole("button",{name:"Confirm retry"})).toBeVisible()});
test("cancel preserves failed item",async({page})=>{await mock(page);await connect(page);await page.getByRole("button",{name:"Retry",exact:true}).click();await page.getByRole("button",{name:"Cancel"}).click();await expect(page.locator("#failed tr")).toHaveCount(1)});
test("confirm refreshes failed jobs and activity",async({page})=>{await mock(page);await connect(page);await page.getByRole("button",{name:"Retry",exact:true}).click();await page.getByRole("button",{name:"Confirm retry"}).click();await expect(page.locator("#status")).toContainText("queued")});
test("failed endpoint error stays isolated",async({page})=>{await mock(page,{failedStatus:503});await connect(page);await expect(page.locator("#failedError")).toContainText("could not be loaded");await expect(page.locator("#queue")).toContainText("Queued")});
test("audit activity renders",async({page})=>{await mock(page);await connect(page);await expect(page.locator("#log")).toContainText("job.retry")});
test("mobile viewport has no page overflow",async({page})=>{await page.setViewportSize({width:390,height:844});await mock(page);await connect(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
test("keyboard navigation reaches connect and refresh",async({page})=>{await mock(page);await page.goto("/admin");await page.locator("#adminKey").focus();await page.locator("#adminKey").fill("valid");await page.keyboard.press("Tab");await page.keyboard.press("Enter");await expect(page.locator("#refresh")).toBeFocused()});
