import{expect,test}from"@playwright/test";const token="a".repeat(43);async function mock(page,{signedIn=false,verified=true,invalidReset=false}={}){let currentVerified=verified;await page.route("**/api/**",async route=>{const url=new URL(route.request().url()),path=url.pathname,json=(status,body)=>route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});if(path==="/api/auth/config")return json(200,{registrationMode:"public",emailVerificationRequired:true});if(path==="/api/auth/me")return signedIn?json(200,{user:{id:"u",email:"u@example.test",createdAt:"2026-09-01T00:00:00.000Z",emailVerified:currentVerified}}):json(401,{error:{code:"AUTHENTICATION_REQUIRED"}});if(path==="/api/auth/password-reset/request")return json(202,{accepted:true});if(path==="/api/auth/password-reset/confirm")return invalidReset?json(400,{error:{code:"INVALID_PASSWORD_RESET_TOKEN"}}):route.fulfill({status:204});if(path==="/api/auth/email-verification/request")return json(202,{accepted:true});if(path==="/api/auth/email-verification/confirm"){currentVerified=true;return route.fulfill({status:204})}if(path==="/api/audits/quota")return json(200,{plan:"free",quota:{limit:3,used:0,remaining:3,periodStart:"2026-09-01T00:00:00.000Z",resetsAt:"2026-10-01T00:00:00.000Z"},features:{}});if(path==="/api/audits/history")return json(200,{audits:[],page:{nextCursor:null}});if(path==="/api/audits")return json(403,{error:{code:"EMAIL_VERIFICATION_REQUIRED",message:"Verify your email."}});return json(404,{error:{code:"NOT_FOUND"}})})}
test("forgot password opens",async({page})=>{await mock(page);await page.goto("/");await page.getByRole("button",{name:"Forgot password?"}).click();await expect(page.locator("#passwordResetRequestForm")).toBeVisible()});
test("reset request shows generic success",async({page})=>{await mock(page);await page.goto("/");await page.getByRole("button",{name:"Forgot password?"}).click();await page.locator("#resetEmail").fill("u@example.test");await page.getByRole("button",{name:"Send reset link"}).click();await expect(page.locator("#authError")).toContainText("If an account exists")});
test("reset fragment is scrubbed immediately",async({page})=>{await mock(page);await page.goto(`/#reset-password=${token}`);await expect(page).not.toHaveURL(/reset-password/);await expect(page.locator("#passwordResetConfirmForm")).toBeVisible()});
test("reset form submits matching password",async({page})=>{await mock(page);await page.goto(`/#reset-password=${token}`);await page.locator("#resetPassword").fill("new password value");await page.locator("#resetPasswordConfirm").fill("new password value");await page.getByRole("button",{name:"Update password"}).click();await expect(page.locator("#authError")).toContainText("Password updated")});
test("successful reset returns to login",async({page})=>{await mock(page);await page.goto(`/#reset-password=${token}`);await page.locator("#resetPassword").fill("new password value");await page.locator("#resetPasswordConfirm").fill("new password value");await page.getByRole("button",{name:"Update password"}).click();await expect(page.locator("#loginEmail")).toBeFocused()});
test("invalid reset token is safe",async({page})=>{await mock(page,{invalidReset:true});await page.goto(`/#reset-password=${token}`);await page.locator("#resetPassword").fill("new password value");await page.locator("#resetPasswordConfirm").fill("new password value");await page.getByRole("button",{name:"Update password"}).click();await expect(page.locator("#authError")).toContainText("invalid or expired")});
test("unverified user sees verification state",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto("/");await expect(page.getByText("Verify your email to run audits.")).toBeVisible()});
test("unverified state hides audit entry",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto("/");await expect(page.locator("#auditForm")).toBeHidden()});
test("resend verification works",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto("/");await page.getByRole("button",{name:"Resend verification email"}).click();await expect(page.locator("#authError")).toContainText("requested")});
test("verification fragment is scrubbed immediately",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto(`/#verify-email=${token}`);await expect(page).not.toHaveURL(/verify-email/)});
test("verification refreshes current user",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto(`/#verify-email=${token}`);await expect(page.locator("#authError")).toContainText("Email verified")});
test("audit becomes available after verification",async({page})=>{await mock(page,{signedIn:true,verified:false});await page.goto(`/#verify-email=${token}`);await expect(page.locator("#auditForm")).toBeVisible()});
test("tokens are absent from persistence cookies and DOM",async({page,context})=>{await mock(page);await page.goto(`/#reset-password=${token}`);expect(await page.evaluate(t=>({local:Object.values(localStorage).includes(t),session:Object.values(sessionStorage).includes(t),dom:document.documentElement.outerHTML.includes(t)}),token)).toEqual({local:false,session:false,dom:false});expect((await context.cookies()).some(c=>c.value.includes(token))).toBe(false)});
test("mobile has no new horizontal overflow",async({page})=>{await page.setViewportSize({width:390,height:844});await mock(page);await page.goto("/");await page.getByRole("button",{name:"Forgot password?"}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true)});
test("reset flow is keyboard operable",async({page})=>{await mock(page);await page.goto("/");await page.getByRole("button",{name:"Forgot password?"}).focus();await page.keyboard.press("Enter");await expect(page.locator("#resetEmail")).toBeFocused()});
